"""add dossiers + Run.dossier_id

Revision ID: 44db940bfa53
Revises: 3d6d1fec4257
Create Date: 2026-05-25 16:35:03.506018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44db940bfa53'
down_revision: Union[str, Sequence[str], None] = '3d6d1fec4257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_client_id'), 'dossiers', ['client_id'], unique=False)
    op.create_index('ix_dossiers_client_label', 'dossiers', ['client_id', 'label'], unique=False)
    op.create_index(op.f('ix_dossiers_organization_id'), 'dossiers', ['organization_id'], unique=False)
    op.add_column('runs', sa.Column('dossier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_runs_dossier_id'), 'runs', ['dossier_id'], unique=False)
    op.create_foreign_key(None, 'runs', 'dossiers', ['dossier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_index(op.f('ix_runs_dossier_id'), table_name='runs')
    op.drop_column('runs', 'dossier_id')
    op.drop_index(op.f('ix_dossiers_organization_id'), table_name='dossiers')
    op.drop_index('ix_dossiers_client_label', table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_client_id'), table_name='dossiers')
    op.drop_table('dossiers')
    # ### end Alembic commands ###
